import type { Metadata } from "next";
import Newsletter from "@/components/Newsletter";
import DefaultLayout from "@/components/Layouts/DefaultLayout";
import Breadcrumb from "@/components/Breadcrumb";
import React from "react";
import TokenSale from "@/components/TokenSale";

export const metadata: Metadata = {
  title:
    "Token Sale | Crypto - Next.js Template",
  description: "Generated by create next app",
};

export default function TokenSalePage() {
  return (
    <>
      <DefaultLayout>
        <Breadcrumb pageName="Token Sale" />

        <TokenSale />
        <Newsletter />
      </DefaultLayout>
    </>
  );
}
